### ISSUE TITLE
Flutter web: Connectycube : P2P :Not disposing camera of User 2 on video call end when User 1 ends the call 

### ISSUE THREAD

**Issue by paddymahadeva** [ConnectyCube/connectycube-flutter-call-kit#100]
We are using the below code as given in in the same P2P calling project

_callClient!.onSessionClosed = (callSession) {
      if (_currentCall != null &&
          _currentCall!.sessionId == callSession.sessionId) {
        _currentCall = null;
        CallKitManager.instance.processCallFinished(callSession.sessionId);
      }
    };

This code is correctly invoked at User 2's end when User 1 ends the call.  The call ends as expected for both users and the page transitions as expected. But the light next to camera remains on  and the browser tab indicates that the camera is still on.  

This issue is happening on both chrome and edge browsers and is reproducing with P2P calling sample project hosted at https://github.com/ConnectyCube/connectycube-flutter-samples.git

**Comment by TatankaConCube** [comment]
could you please fill in all required fields on the creation issue step? What OS do you use for building the app? Do you use the latest version of our SDK and the sample? Please provide steps on how can we reproduce it on our side.

**Comment by TatankaConCube** [comment]
@paddymahadeva please try the new version ([2.5.3](https://pub.dev/packages/connectycube_sdk/versions/2.5.3)), there we did some improvements for local media stream initialization and disposal of.

we will update our samples later for applying these fixes

**Comment by paddymahadeva** [comment]
Hey @TatankaConCube  thanks for your response, we are upgrading to 2.5.3 and will report back by next 2 days. 

The build is made from windows OS and deployed to firebase 

The connectycube versions we are on 

connectycube_flutter_call_kit: ^2.2.4
  connectycube_sdk: ^2.5.0


BTW, We are building for the web. This issue is faced on web browsers, specifically edge & Chrome.  It works fine on Firefox and Safari.

**Comment by paddymahadeva** [comment]
The issue still persists in edge after upgrade. We found the below exception there when we ended the call

0  Uncaught MissingPluginException(No implementation found for method reportCallEnded on channel connectycube_flutter_call_kit.methodChannel)
    at Object.v (https://carefirst360-demo.web.app/main.dart.js:4770:3)
    at https://carefirst360-demo.web.app/main.dart.js:141521:15
    at bIs.a (https://carefirst360-demo.web.app/main.dart.js:6045:62)
    at bIs.$2 (https://carefirst360-demo.web.app/main.dart.js:64769:14)
    at bGQ.$1 (https://carefirst360-demo.web.app/main.dart.js:64763:21)
    at bBB.b5f (https://carefirst360-demo.web.app/main.dart.js:65768:34)
    at bBB.X6 (https://carefirst360-demo.web.app/main.dart.js:65770:21)
    at biS.$0 (https://carefirst360-demo.web.app/main.dart.js:65150:11)
    at Object.K0 (https://carefirst360-demo.web.app/main.dart.js:6170:40)
    at aN.ww (https://carefirst360-demo.web.app/main.dart.js:65083:3)
v @ main.dart.js:4770

Could this be the reason?

**Comment by paddymahadeva** [comment]
The issue still persists in edge after upgrade. We found the below exception there when we ended the call

0 Uncaught MissingPluginException(No implementation found for method reportCallEnded on channel connectycube_flutter_call_kit.methodChannel)
at Object.v ()

Could this be the reason?

**Comment by TatankaConCube** [comment]
@paddymahadeva could you please try our test branch [improvements_for_p2p](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/feature/improvements_for_p2p) where we reworked the UI and simplified the local stream initialization and disposing of. And please use the latest version of our SDK (2.5.5 at this moment).

> Could this be the reason

no, it shouldn't, it is just the side effect of not supporting the Web platform by the  `connectycube_flutter_call_kit` plugin

**Comment by TatankaConCube** [comment]
@paddymahadeva had you a chance to check it? the issue is that the issue doesn't reproduce on our side

**Comment by paddymahadeva** [comment]
Hi @TatankaConCube not yet. We have not tried with test branch. Will report back in the coming week. For us the issue is reproducing with the P2P example project also.
