### ISSUE TITLE
Incoming Callkit notification not triggering when app is terminated

### ISSUE THREAD

**Issue by muj-i** [ConnectyCube/connectycube-flutter-call-kit#149]
this is the error log when app is terminated and a call notification arrived from FCM. It didn't trigger the callkit incoming call notification rather logging this
```
I/flutter (21552): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (21552): PlatformException(java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly., Exception, Cause: null, Stacktrace: java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly.
I/flutter (21552):      at io.flutter.plugins.firebase.core.i.v(Unknown Source:12)
I/flutter (21552):      at io.flutter.plugins.firebase.core.i.l(Unknown Source:0)
I/flutter (21552):      at io.flutter.plugins.firebase.core.b.run(Unknown Source:4)
I/flutter (21552):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
I/flutter (21552):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
I/flutter (21552):      at java.lang.Thread.run(Thread.java:1012)
I/flutter (21552): , null)
```

This is my FCM background handler
This works absolutely fine when the app is in the background but not terminated, but it can't trigger the CallKit when the app is terminated.
```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
   await Firebase.initializeApp();
  

  String docName = '';
  String docImage = '';
  String uuid = '';

  if (message.data['type'] == 'call') {
  docName = message.data['doc_name'];
  docImage = message.data['doc_image'];
  uuid = message.data['uuid'];

  var callerId = Random().nextInt(999999);
  var opponentsIds = {Random().nextInt(999999)};
    CallEvent callEvent = CallEvent(
      sessionId: uuid,
      callType: 0,
      callerId: callerId,
      callerName: docName,
      opponentsIds: {opponentsIds},
      callPhoto: docImage,
    );
    ConnectycubeFlutterCallKit.showCallNotification(callEvent);
  } 
  dev.log("Handling a background message: ${message.messageId}");
}
```

**Comment by TatankaConCube** [comment]
Unfortunately, I can't localize the issue because I can't see any plugin's code in the provided stacktrtace.

**Comment by muj-i** [comment]
solution is 
add this 
```
await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
 ```
 instead of 
 ```
 await Firebase.initializeApp();
 ```

**Comment by muj-i** [comment]
closing as complete
