### ISSUE TITLE
Error while ConnectycubeFlutterCallKit.showCallNotification()

### ISSUE THREAD

**Issue by morfair** [ConnectyCube/connectycube-flutter-call-kit#29]
I get FCM message in background and run for test purpose:
```
ConnectycubeFlutterCallKit.showCallNotification(
      sessionId: Uuid().v4(),
      callType: 2,
      callerId: 714,
      callerName: "Caller Name",
      opponentsIds: {101}.toSet(),
    );
```
And get error:
```
I/flutter (18554): Handling a background message 0:1636988663550498%7fab33907fab3390
E/AndroidRuntime(18554): FATAL EXCEPTION: main
E/AndroidRuntime(18554): Process: {com.example.app.rc_intercom, PID: 18554
E/AndroidRuntime(18554): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app.rc_intercom/com.connectycube.flutter.connectycube_flutter_call_kit.IncomingCallActivity}: java.lang.IllegalStateException: findViewById(resources.g…txt", "id", packageName)) must not be null
E/AndroidRuntime(18554): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
E/AndroidRuntime(18554): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
E/AndroidRuntime(18554): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(18554): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
E/AndroidRuntime(18554): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(18554): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(18554): 	at android.app.ActivityThread.main(ActivityThread.java:6517)
E/AndroidRuntime(18554): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18554): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime(18554): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/AndroidRuntime(18554): Caused by: java.lang.IllegalStateException: findViewById(resources.g…txt", "id", packageName)) must not be null
E/AndroidRuntime(18554): 	at com.connectycube.flutter.connectycube_flutter_call_kit.IncomingCallActivity.initUi(IncomingCallActivity.kt:123)
E/AndroidRuntime(18554): 	at com.connectycube.flutter.connectycube_flutter_call_kit.IncomingCallActivity.onCreate(IncomingCallActivity.kt:62)
E/AndroidRuntime(18554): 	at android.app.Activity.performCreate(Activity.java:6915)
E/AndroidRuntime(18554): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
E/AndroidRuntime(18554): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
E/AndroidRuntime(18554): 	... 9 more
I/Process (18554): Sending signal. PID: 18554 SIG: 9
Lost connection to device.

```

**Comment by TatankaConCube** [comment]
Have you made any changes in `activity_incoming_call.xml`?

**Comment by morfair** [comment]
@TatankaConCube 
No. I don't even know where this file is...

**Comment by Kevy235** [comment]
@TatankaConCube , 
Hi there, 
i'm facing the same problem, could you please help ?

**Comment by TatankaConCube** [comment]
@Kevy235 @morfair do you reproduce it in the latest version?

**Comment by Kevy235** [comment]
@TatankaConCube  thank you to reply, yes i did  but when the app is terminated the accept call dosn't work, sometimes app crashed.
