### ISSUE TITLE
App crash when phone is locked

### ISSUE THREAD

**Issue by nmdv24** [ConnectyCube/connectycube-flutter-call-kit#40]
When phone is locked, IncomingCallActivity crashed in only release mode

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{***.package.***/com.connectycube.flutter.connectycube_flutter_call_kit.IncomingCallActivity}: android.view.InflateException: Binary XML file line #1 in ***.package.***:layout/activity_incoming_call: Binary XML file line #1 in ***.package.***:layout/activity_incoming_call: Error inflating class x
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4037)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4203)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)`

**Comment by TatankaConCube** [comment]
looks like Proguard related issue, try to add the ignoring Android classes to the proguard rules.
